#
# This is a Vigie config file example used to run vigie.dev/demo
# This config file need to be load by a Vigie binary
# vigie run --config vigieconf.toml
#

apiversion = 0.5

[host]
  name = "Demo Instance"
  url = ""
  [host.tags]
    k = "v"

[git]
  clone = true
  repo = "https://github.com/Vincoll/vigie-demo-test"
  path = "/tmp/vigie"

[testfiles]
  included = ['/tmp/vigie/test']
  excluded = ['']

[variables]
  variables = ['','']
  included = ['/tmp/vigie/var']
  excluded = ['']
  fromenv = false

[api]
  enable = true
  port = 6680

[log]
  stdout = true
  logfile = false
  level = "debug"
  filePath = "/tmp/vigie.log"

[influxdb]
  enable = false
  addr = "http://influxdb:8086"
  user = "user"
  password = "user"
  database = "vigie"

[alerting]
  enable = false
  interval = "10s"
  reminder = "8h"
  [alerting.email]
    to = ""
    from = ""
    username = ""
    password = ""
    smtp  = ""
    port = 587
  [alerting.discord]
    hook = "https://discordapp.com/api/webhooks/000000000000000/aaaaaazzzzzzz"

